[versions]
kotlin = "2.0.0"
shadow = "8.1.1"
simpleCloudController = "0.0.27-EXPERIMENTAL"
# implementation("org.incendo:cloud-paper:2.0.0-beta.8")
paper = "1.20.6-R0.1-SNAPSHOT"
cloudCommands = "2.0.0-beta.8"

[libraries]
kotlinJvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
paperApi = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
cloudMinecraftExtras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloudCommands" }
cloudPaper = { module = "org.incendo:cloud-paper", version.ref = "cloudCommands" }

simpleCloudControllerApi = { module = "app.simplecloud.controller:controller-api", version.ref = "simpleCloudController" }
simpleCloudControllerShared = { module = "app.simplecloud.controller:controller-shared", version.ref = "simpleCloudController" }

[bundles]
simpleCloudController = ["simpleCloudControllerApi", "simpleCloudControllerShared"]
cloudPaper = ["cloudPaper", "cloudMinecraftExtras"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }