package app.simplecloud.npc.shared.enums

/**
 * @author Niklas Nieberler
 */

enum class LabyEmote(val key: Int, val displayName: String) {

    BACKFLIP(2, "Backflip"),
    DAB(3, "Dab"),
    HELLO(4, "Hello"),
    BOW_THANKS(5, "Bow thanks"),
    HYPE(6, "Hype"),
    TRYING_TO_FLY(7, "Trying to fly"),
    INFINITY_SIT(8, "Infinity sit"),
    ZOMBIE(11, "Zombie"),
    HULA_HOOP(13, "Hula Hoop"),
    CALLING(14, "Calling"),
    FACEPALM(15, "Facepalm"),
    BRUSH_YOUR_SHOULDERS(18, "Brush your shoulders"),
    SPLIT(19, "Split"),
    SALUTE(20, "Salute"),
    BALLERINA(22, "Ballerina"),
    HANDSTAND(31, "Handstand"),
    HELICOPTER(32, "Helicopter"),
    HOLY(33, "Holy"),
    WAVEOVER(34, "Waveover"),
    DEEPER_DEEPER(36, "Deeper deeper"),
    KARATE(37, "Karate"),
    MOONWALK(38, "Moonwalk"),
    FREEZING(40, "Freezing"),
    JUBILATION(41, "Jubilation"),
    TURTLE(43, "Turtle"),
    HEADSPIN(45, "Headspin"),
    INFINITY_DAB(46, "Infinity Dab"),
    CHICKEN(47, "Chicken"),
    THE_FLOSS(49, "The Floss"),
    THE_MEGA_THRUST(50, "The mega thrust"),
    THE_CLEANER(51, "The cleaner"),
    BRIDGE(52, "Bridge"),
    MILK_THE_COW(53, "Milk the cow"),
    RURIK(54, "Rurik"),
    WAVE(55, "Wave"),
    MONEY_RAIN(57, "Money rain"),
    THE_POINTER(59, "The pointer"),
    FRIGHTENING(60, "Frightening"),
    SAD(61, "Sad"),
    AIR_GUITAR(62, "Air guitar"),
    WITCH(63, "Witch"),
    LEFT(69, "Left"),
    RIGHT(70, "Right"),
    BUUUH(74, "Buuuh"),
    SPITTING_BARS(75, "Spitting bars"),
    COUNT_MONEY(76, "Count money"),
    HUG(77, "Hug"),
    APPLAUSE(78, "Applause"),
    BOXING(79, "Boxing"),
    SHOOT(83, "Shoot"),
    THE_POINTING_MAN(84, "The pointing man"),
    HEART(85, "Heart"),
    NEAR_THE_FALL(86, "Near the fall"),
    WAITING(89, "Waiting"),
    PRAISE_YOUR_ITEM(92, "Praise your item"),
    LOOK(93, "Look"),
    I_LOVE_YOU(97, "I love you"),
    SARCASTIC_CLAP(98, "Sarcastic clap"),
    YOU(101, "You"),
    HEAD_ON_WALL(105, "Head on wall"),
    BALANCE(112, "Balance"),
    LEVELUP(113, "Levelup"),
    TAKE_THE_L(114, "Take the L"),
    MY_IDOL(121, "My idol"),
    AIRPLANE(122, "Airplane"),
    EAGLE(124, "Eagle"),
    JOB_WELL_DONE(126, "Job well done"),
    ELEPHANT(128, "Elephant"),
    PRESENT(130, "Present"),
    EYES_ON_YOU(131, "Eyes on you"),
    BOW_DOWN(133, "Bow down"),
    MANEKI_NEKO(134, "Maneki-neko"),
    CONDUCTOR(135, "Conductor"),
    DIDI_CHALLENGE(136, "Didi challenge"),
    SNOW_ANGEL(137, "Snow Angel"),
    SNOWBALL(138, "Snowball"),
    SPRINKLER(139, "Sprinkler"),
    CALCULATED(140, "Calculated"),
    ONE_ARMED_HANDSTAND(141, "One-armed handstand"),
    EAT(142, "Eat"),
    SHY(143, "Shy"),
    SWIMMING_ON_THE_GROUND(144, "Swimming On The Ground"),
    SIT_UPS(145, "Sit-Ups"),
    BREAKDANCE(146, "Breakdance"),
    MINDBLOW(148, "Mindblow"),
    FALL(149, "Fall"),
    T_POSE(150, "T Pose"),
    JUMPING_JACK(153, "Jumping Jack"),
    BACKSTROKE(154, "Backstroke"),
    ICE_HOCKEY(156, "Ice-Hockey"),
    LOOK_AT_FIREWORKS(157, "Look at fireworks"),
    FINISH_THE_TREE(158, "Finish the tree"),
    ICE_SKATING(159, "Ice-Skating"),
    FANCY_FEET(161, "Fancy Feet"),
    RONALDO(162, "Ronaldo"),
    TRUE_HEART(163, "True Heart"),
    PUMPERNICKEL(164, "Pumpernickel"),
    BABY_SHARK(166, "Baby Shark"),
    OPEN_PRESENT(167, "Open present"),
    DJ(170, "Dj"),
    HAVE_TO_PEE(171, "Have to pee"),
    SNEEZE(173, "Sneeze"),
    CHEERLEADER(178, "Cheerleader"),
    NARUTO_RUN(180, "Naruto Run"),
    PATI_PATU(181, "Pati Patu"),
    AXE_SWING(182, "Axe Swing"),
    FUSION_LEFT(183, "Fusion Left"),
    FISHING(184, "Fishing"),
    FUSION_RIGHT(185, "Fusion Right"),
    BREATHLESS(187, "Breathless"),
    GENKIDAMA(189, "Genkidama"),
    SINGER(191, "Singer"),
    MAGIKARP(192, "Magikarp"),
    RAGE(193, "Rage"),
    SLAP(194, "Slap"),
    AIR_KISSES(195, "Air kisses"),
    KNOCKOUT(196, "Knockout"),
    MATRIX(197, "Matrix"),
    JETPACK(198, "Jetpack"),
    GOLF(200, "Golf"),
    STADIUM_WAVE(201, "Stadium wave"),
    KICKBOXER(202, "Kickboxer"),
    HANDSHAKE(203, "Handshake"),
    CLEANING_THE_FLOOR(204, "Cleaning the floor"),
    SWEAT_WIPE(209, "Sweat Wipe"),
    HOKUSPOKUS(213, "Hokuspokus"),
    THE_BAT(215, "The Bat"),
    SLIPPERY_GROUND(216, "Slippery ground"),
    PENGUIN_WALK(217, "Penguin walk"),
    SINKING_IN_THE_SNOW(219, "Sinking in the snow"),
    BSEFSFDGDH(278, "bsefsfdgdh"),
    SPYGLASS(281, "Spyglass"),
    GAMING_CHAIR_SIT(282, "Gaming Chair Sit"),
    UWU_GAMING_CHAIR_SIT(283, "UwU Gaming Chair Sit"),
    MAGIC_BROOM(285, "Magic Broom"),
    EGG_HIDE(288, "egg hide"),
    FROZEN(289, "Frozen"),
    SNOWMAN_HIDE(290, "Snowman Hide"),
    METEOR_STRIKE(291, "Meteor Strike"),
    KISS(293, "Kiss"),
    HAMMOCK(294, "Hammock"),
    A_BAKED_BEAN(295, "A Baked Bean"),
    WATERING(298, "Watering"),
    FIRE_BENDER(299, "Fire Bender"),
    PRESENT_FOR_YOU(300, "Present for you"),
    RAINCLOUD(301, "Raincloud"),
    LANTERN_FLIGHT(302, "Lantern flight"),
    WORSHIP(305, "Worship"),
    SURFBOARD(307, "Surfboard"),
    SUNBED(308, "Sunbed"),
    WATER_GUN(309, "Water Gun"),
    UKULELE(311, "Ukulele"),
    ICE_CREAM(312, "Ice Cream"),
    MAGIC_TRICK(314, "Magic Trick"),
    FIREBALL(316, "Fireball"),
    PURPLE_SUSANOO(317, "Purple Susanoo"),
    LEVITATING(318, "Levitating"),
    DINNERBONE(319, "Dinnerbone"),
    RED_SUSANOO(320, "Red Susanoo"),
    BLUE_SUSANOO(321, "Blue Susanoo"),
    GREEN_SUSANOO(322, "Green Susanoo"),
    CYAN_SUSANOO(323, "Cyan Susanoo"),
    HEAD_OFF(325, "Head Off"),
    TWO_DIMENSIONAL(326, "Two-Dimensional"),
    POSSESSED(328, "Possessed"),
    WEREWOLF_WALK(329, "Werewolf Walk"),
    KILLER_CHASE(330, "Killer Chase"),
    GRIDDY(333, "Griddy"),
    SPEED_ICE_SKATING(334, "Speed Ice Skating"),
    SNOWBALL_THROW(335, "Snowball Throw"),
    DRIFT_KART_PURPLE(344, "Drift Kart Purple"),
    DRIFT_KART_PINK(345, "Drift Kart Pink"),
    DRIFT_KART_YELLOW(346, "Drift Kart Yellow"),
    DRIFT_KART_BLUE(347, "Drift Kart Blue"),
    DRIFT_KART_RED(349, "Drift Kart Red"),
    DRIFT_KART_GREEN(350, "Drift Kart Green"),
    TRASH(356, "Trash"),
    OFFROAD_BIKE_RED(358, "Offroad Bike Red"),
    OFFROAD_BIKE_BLUE(359, "Offroad Bike Blue"),
    OFFROAD_BIKE_PURPLE(360, "Offroad Bike Purple"),
    OFFROAD_BIKE_PINK(361, "Offroad Bike Pink");

    companion object {
        fun get(name: String): LabyEmote? {
            return entries.firstOrNull { it.displayName.lowercase().replace(" ", "_").equals(name, true) }
        }
    }

}